[client]
showSidebarNavigation = false

[[theme.fontFaces]]
family = "Poppins"
url = "./static/Poppins-Medium.ttf"
weight=500
style="normal"

[[theme.fontFaces]]
family = "Poppins"
url = "./static/Poppins-Black.ttf"
weight=900
style="normal"

[[theme.fontFaces]]
family = "Poppins"
url = "./static/Poppins-Italic.ttf"
weight=500
style="italic"

[theme]
base = "light"
primaryColor = "#084c61"
backgroundColor = "white"
textColor = "#084c61"
codeBackgroundColor = "#56a3a6"
font = "Poppins"
baseRadius="full"
showWidgetBorder = false




